### ISSUE TITLE
Full unload

### ISSUE THREAD

**Issue by Jofairden** [DRKV333/MechScope#1]
https://github.com/DRKV333/MechScope/blob/ab0cb5292029b09615994f87a9eeed96d83ae414/MechScope.cs#L76-L84

You should unload various static variables here as well such as keyToggle/keyStep etc, for a full unload.
Great mod btw.

**Comment by DRKV333** [comment]
So, after adding this to `Unload()`:
```
keyToggle = null;
keyStep = null;
keyAutoStep = null;
keySettings = null;
```
The mod class no longer sticks around and gets garbage collected properly. This stops the `MechScope not fully unloaded during unload.` message from appearing in the log. However, there are still things that stayed in memory. The `SettingsUI`, the associated `UIElement`s and two dictionaries from `VisualizerWorld`. 
Should I be worried about those? I mean, in this case they are easy to get rid of, but I ran into more complex issues related to this in other projects. (There are also two lambda closure classes that stay loaded, but I cant do anything about that...) So basically my question is, how worried should I be about unloading everything?

**Comment by Jofairden** [comment]
You should generally unload everything you can that you do not want to persist between reloads.

**Comment by DRKV333** [comment]
Well, I think I got pretty much everything unloaded in a85a039ede41ee01f5ddef5271cd03f8f3776931. Thanks for your time. 😄
